from bag import Bag


def testAll():
    b = Bag()
    assert(b.isEmpty() == True)
    assert(b.size() == 0)
    b.add(5)
    b.add(1)
    b.add(10)
    b.add(7)
    b.add(1)
    b.add(11)
    b.add(-3)
    assert(b.size() == 7)
    assert(b.search(10) == True)
    assert(b.search(16) == False)
    assert(b.nrOccurrences(1) == 2)
    assert(b.nrOccurrences(7) == 1)
    assert(b.remove(1) == True)
    assert(b.remove(6) == False)
    assert(b.size() == 6)
    assert(b.nrOccurrences(1) == 1)
    it = b.iterator()
    it.first()
    while it.valid():
        e = it.getCurrent()
        it.next()
    assert(it.valid() == False)
    it.first()
    assert(it.valid() == True)
